# 多アカウント設定（拡張）

accounts:
  - id: Maya19960330
    handle: "Maya19960330"
    browser: { user_data_dir: "profile/Maya19960330", headless: true }
    features: { like: true, retweet: true, comment: true, bookmark: true }
    # Maya専用のコメント設定
    comment_config:
      default_priority: time_based
      time_schedule:
        morning: # 5-10時
          priority: greet
          fallback: ai_content
        day: # 10-17時
          priority: ai_content
          fallback: greet
        evening: # 17-22時
          priority: ai_content
          fallback: simple
        night: # 22-5時
          priority: simple
          fallback: greet
      ai_personality: maya
      response_style: friendly_casual
    policies:
      sources: ["mentions", "my_threads"]
      only_if_my_thread: true
      reply_num_max: 0
      tweet_selection: { top_n: 2 }
      user_switch_interval_seconds: 5
      human_like_on_start:
        enabled: true
        sequence:
          - handle: Maya19960330
            top_n: 10
            dwell_seconds: 10
          - handle: ren_ai_coach
            top_n: 10
            dwell_seconds: 10
          - handle: self
            top_n: 1
            dwell_seconds: 10
      per_target_prefetch:
        enabled: true
        top_n: 5
        dwell_seconds: 5
      per_target:
        ren_ai_coach: { actions: [like, bookmark, retweet] }
        zero_divide_00: { actions: [like, bookmark] }
        285smzgcsq36129:
          actions: [like, comment]
          nickname: "七宝ちゃん"
          comment_config: inherit  # Maya用のcomment_configを継承
          greet: auto
        2nd_karen_ai:
          actions: [like, comment]
          nickname: "かれんちゃん"
          comment_config: inherit  # Maya用のcomment_configを継承
          greet: auto
        ai8263353539674:
          actions: [like, comment]
          nickname: "みうちゃん"
          comment_config: inherit  # Maya用のcomment_configを継承
          greet: { mode: fixed, text: "はいさーい" }
        aichan_lovelyai:
          actions: [like, comment]
          nickname: "あいちゃん"
          comment_config: inherit  # Maya用のcomment_configを継承
          greet: auto
        aiidol_misaki:
          actions: [like, comment]
          nickname: "みさきちゃん"
          greet: auto
        aisanmaru30:
          actions: [like, comment]
          nickname: "さんまるちゃん"
          greet: auto
        aoi_cocona:
          actions: [like, comment]
          nickname: "ここなちゃん"
          greet: auto
        disney_ikitasi:
          actions: [like, comment]
          nickname: "ゆりちゃん"
          greet: auto
        erutea_ai37:
          actions: [like, comment]
          nickname: "えるちゃん"
          greet: auto
        famous4771:
          actions: [like, comment]
          nickname: "みかちゃん"
          greet: auto
        fancy_pop_pic:
          actions: [like, comment]
          nickname: "ふぁぽちゃん"
          greet: auto
        frogblue1235951:
          actions: [like, comment]
          nickname: "あおさん"
          greet: auto
        girl_ai001:
          actions: [like, comment]
          nickname: "せなちゃん"
          greet: auto
        hinachan_ai:
          actions: [like, comment]
          nickname: "ひなちゃん"
          greet: auto
        hisyoka_joshi:
          actions: [like, comment]
          nickname: "秘書ちゃん"
          greet: auto
        honey_bee_610:
          actions: [like, comment]
          nickname: "ハニちゃん"
          greet: auto
        ikayaki009:
          actions: [like, comment]
          nickname: "ばいちゃん"
          greet: auto
        kasumi_haru66:
          actions: [like, comment]
          nickname: "はるねちゃん"
          greet: auto
        kzn802:
          actions: [like, comment]
          nickname: "はっちゃん"
          greet: auto
        lowleg_cotton:
          actions: [like, comment]
          nickname: "ローレルちゃん"
          greet: auto
        manami_ofp:
          actions: [like, comment]
          nickname: "まなみちゃん"
          greet: auto
        naginokobeya:
          actions: [like, comment]
          nickname: "なぎちゃん"
          greet: auto
        natsu_natsuai:
          actions: [like, comment]
          nickname: "なっちゃん"
          greet: auto
        reina_bb00:
          actions: [like, comment]
          nickname: "れいなちゃん"
          greet: auto
        ren_ai0202:
          actions: [like, comment]
          nickname: "れんちゃん"
          greet: auto
        rezaki75085:
          actions: [like, comment]
          nickname: "るいちゃん"
          greet: auto
        rinaaltsweet:
          actions: [like, comment]
          nickname: "みかちゃん"
          greet: auto
        saiyo_jp:
          actions: [like, comment]
          nickname: "ゆなちゃん"
          greet: auto
        sakuaicute_girl2:
          actions: [like, comment]
          nickname: "さくちゃん"
          greet: auto
        sakura_xsecret:
          actions: [like, comment]
          nickname: "さくらちゃん"
          greet: auto
        seducerina:
          actions: [like, comment]
          nickname: "りなちゃん"
          greet: auto
        sweet_momo_0415:
          actions: [like, comment]
          nickname: "ももちゃん"
          greet: auto
        tuyahimefukujyu:
          actions: [like, comment]
          nickname: "ふくじゅちゃん"
          greet: auto
        yualovedays:
          actions: [like, comment]
          nickname: "ゆあちゃん"
          greet: auto
        yv6lwzy7tb41253:
          actions: [like, comment]
          nickname: "コネリちゃん"
          greet: auto
    rate_limits: { like_per_hour: 0, retweet_per_hour: 0, comment_per_hour: 0, bookmark_per_hour: 0, min_interval_seconds: 20 }
