# 多アカウント設定（拡張）

accounts:
  - id: nyukimi_08
    handle: "nyukimi_08"
    browser: { user_data_dir: "profile/nyukimi_08", headless: false }
    features: { like: true, retweet: true, comment: true, bookmark: true }
    policies:
      sources: ["mentions", "my_threads"]
      only_if_my_thread: true
      reply_num_max: 0
      tweet_selection: { top_n: 2 }
      user_switch_interval_seconds: 5
      human_like_on_start:
        enabled: true
        sequence:
          - handle: Maya19960330
            top_n: 10
            dwell_seconds: 10
          - handle: ren_ai_coach
            top_n: 10
            dwell_seconds: 10
          - handle: self
            top_n: 1
            dwell_seconds: 10
      per_target_prefetch:
        enabled: true
        top_n: 5
        dwell_seconds: 5
      per_target:
        Maya19960330:
          actions: [like, bookmark, retweet, comment]
          fixed_comment: |-
            まやちゃん
            かわいい
        ren_ai_coach: { actions: [like, bookmark, retweet] }
        zero_divide_00: { actions: [like, bookmark] }
    rate_limits: { like_per_hour: 0, retweet_per_hour: 0, comment_per_hour: 0, bookmark_per_hour: 0, min_interval_seconds: 20 }
